site_name: sovenplus docs
site_url: https://cepheidtech.github.io
theme:
  name: material
  custom_dir: overrides
  logo: images/wordmark.svg
  favicon: images/favicon.png
  palette:
      primary: custom
      accent: custom
      scheme: slate
  
  features:
    - header.autohide
    - content.footnote.tooltips

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

extra:
  homepage: /contact

extra_css:
  - stylesheets/extra.css